services:
  backend:
    container_name: tweak-backend
    image: tweak-backend:dev
    build:
      context: .
      dockerfile: tweak-backend/Dockerfile
    restart: always
    ports:
      - "1337:1337"
    networks:
      - tweak-net
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./tweak-backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    container_name: tweak-frontend
    image: tweak-frontend:dev
    build:
      context: .
      dockerfile: tweak-client/Dockerfile
    restart: always
    ports:
      - "4200:4200"
    networks:
      - tweak-net
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./tweak-client:/app
      - frontend_node_modules:/app/node_modules

  mongodb:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tweak-net
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
  backend_node_modules:
  frontend_node_modules:


networks:
  tweak-net:
    driver: bridge
    name: tweak-net
